# Generated by Django 4.2.4 on 2023-09-11 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deps',
            fields=[
                ('Dep_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Dep_name', models.CharField(max_length=100)),
                ('Dep_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=112)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=112)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('postal', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('Dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.deps')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, ' PATIENTS'), (2, 'DOCTORS'), (3, 'RECEPIONISTS'), (4, 'PHARMACISTS'), (5, 'ADMIN')], default='1', null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
