# Generated by Django 4.2.4 on 2024-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extended_description',
            field=models.TextField(blank=True),
        ),
    ]
