# Generated by Django 4.2.4 on 2023-09-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='email',
        ),
        migrations.AddField(
            model_name='docs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
