# Generated by Django 4.2.4 on 2023-09-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0002_remove_docs_is_active_alter_docs_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='phone',
            new_name='phn',
        ),
    ]
