# Generated by Django 4.2.4 on 2024-02-05 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0003_medicine_price_alter_medicine_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False)),
                ('noon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('date_of_prescription', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.docs')),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='eyeapp.medicine')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
