# Generated by Django 4.2.4 on 2023-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0003_remove_phar_email_deps_user_phar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('institution', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('complete_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
    ]
