# Generated by Django 4.2.4 on 2023-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0003_rename_phone_docs_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
