# Generated by Django 4.2.4 on 2024-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
