# Generated by Django 4.2.4 on 2024-02-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0005_prescription_dosages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
    ]
