# Generated by Django 4.2.4 on 2023-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0005_remove_phar_user_phar_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phar',
            name='email',
        ),
        migrations.AddField(
            model_name='docs',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
