# Generated by Django 4.2.4 on 2023-09-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0006_remove_phar_is_active_remove_rep_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phar',
            old_name='phone',
            new_name='phn',
        ),
        migrations.RenameField(
            model_name='rep',
            old_name='phone',
            new_name='phn',
        ),
    ]
