# Generated by Django 4.2.4 on 2023-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0006_remove_phar_email_docs_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='date_of_birth',
            field=models.DateField(max_length=100),
        ),
    ]
