# Generated by Django 4.2.4 on 2024-02-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0007_remove_patienthistory_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
