# Generated by Django 4.2.4 on 2023-09-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0007_alter_docs_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docs',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
