# Generated by Django 4.2.4 on 2023-09-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0009_docs_admin_set_password_phar_admin_set_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=110)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('admin_set_password', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
