# Generated by Django 4.2.4 on 2023-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0011_doctorprofile_email_doctorprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, ' PATIENTS'), (2, 'DOCTORS'), (3, 'RECEPIONISTS'), (4, 'PHARMACISTS'), (5, 'ADMIN')], default='1', null=True),
        ),
    ]
