# Generated by Django 4.2.4 on 2023-10-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0012_medicinecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineCategory',
        ),
    ]
