# Generated by Django 4.2.4 on 2023-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0012_docs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, ' PATIENTS'), (2, 'DOCTORS'), (3, 'RECEPIONISTS'), (4, 'PHARMACISTS'), (5, 'ADMIN')], default='2', null=True),
        ),
    ]
