# Generated by Django 4.2.4 on 2023-09-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0013_alter_docs_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='user',
        ),
    ]
