# Generated by Django 4.2.4 on 2023-10-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0014_medicinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('companyName', models.CharField(max_length=100)),
                ('expiryDate', models.DateField()),
                ('contains', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('MedCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyeapp.medicinecategory')),
            ],
        ),
    ]
