# Generated by Django 4.2.4 on 2023-10-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0016_medicine_is_active_medicinecategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
