# Generated by Django 4.2.4 on 2024-02-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0016_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eyeapp.careeropening'),
        ),
    ]
