# Generated by Django 4.2.4 on 2023-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0019_alter_doctorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_doctors/'),
        ),
    ]
