# Generated by Django 4.2.4 on 2024-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0022_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('witness1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('witness1_age', models.IntegerField(blank=True, null=True)),
                ('witness1_address', models.TextField(blank=True, null=True)),
                ('witness1_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('witness2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('witness2_age', models.IntegerField(blank=True, null=True)),
                ('witness2_address', models.TextField(blank=True, null=True)),
                ('witness2_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('consent_notify_next_of_kin', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
