# Generated by Django 4.2.4 on 2023-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0022_alter_doctorprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
