# Generated by Django 4.2.4 on 2024-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0023_eyedonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyedonor',
            name='witness1_age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyedonor',
            name='witness2_age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
