# Generated by Django 4.2.4 on 2023-09-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0023_doctorprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='birth_date',
        ),
    ]
