# Generated by Django 4.2.4 on 2023-09-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeapp', '0024_remove_doctorprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
